---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates an S3 bucket in the same region where the stack
  is launched and copy the Lambda functions code from original bucket to the new bucket (qs-1r0eejdp7).
Parameters:
  QSS3BucketName:
    Default: ""
    Type: String
  QSS3KeyPrefix:
    Default: ""
    Type: String
  Nonce:
    Default: "1"
    Type: String
    Description: Change to any value re-copy source upon deployment

Resources:
  CopyObjects:
    Properties:
      ServiceToken: !GetAtt CopyObjectsFunction.Arn
      Nonce: !Ref Nonce
      DestBucket: !Ref LambdaArtifactsBucket
      Objects:
        - functions/packages/aws-icc.zip
        - functions/packages/custom-resources.zip
      SourceBucket: !Ref QSS3BucketName
      Prefix: !Ref QSS3KeyPrefix
    Type: AWS::CloudFormation::CustomResource
    DependsOn:
      - CleanUpS3Bucket
  CopyObjectsFunction:
    Properties:
      Code:
        ZipFile: |
          import json
          import logging
          import threading
          import boto3
          import cfnresponse


          def copy_objects(source_bucket, dest_bucket, prefix, objects):
              s3 = boto3.client('s3')
              for o in objects:
                  key = prefix + o
                  copy_source = {
                      'Bucket': source_bucket,
                      'Key': key
                  }
                  if o.find("index.html")!=-1:
                      s3.copy_object(CopySource=copy_source, Bucket=dest_bucket, Key=key,Metadata={"content-type": "text/html"})
                  else:
                      s3.copy_object(CopySource=copy_source, Bucket=dest_bucket, Key=key)


          def delete_objects(bucket):
              client = boto3.client('s3')
              print("Collecting data from" + bucket)
              paginator = client.get_paginator('list_object_versions')
              result = paginator.paginate(Bucket=bucket)
              objects = []
              for page in result:
                  try:
                      for k in page['Versions']:
                          objects.append({'Key': k['Key'], 'VersionId': k['VersionId']})
                      try:
                          for k in page['DeleteMarkers']:
                              version = k['VersionId']
                              key = k['Key']
                              objects.append({'Key': key, 'VersionId': version})
                      except Exception as e:
                          print(e)
                          pass
                      print("deleting objects")
                      client.delete_objects(Bucket=bucket, Delete={'Objects': objects})
                  except Exception as e:
                      print(e)
                      pass
              print("bucket already empty")


          def timeout(event, context):
              logging.error('Execution is about to time out, sending failure response to CloudFormation')
              cfnresponse.send(event, context, cfnresponse.FAILED, {}, None)


          def handler(event, context):
              # make sure we send a failure to CloudFormation if the function is going to timeout
              timer = threading.Timer((context.get_remaining_time_in_millis() / 1000.00) - 0.5, timeout, args=[event, context])
              timer.start()

              print('Received event: %s' % json.dumps(event))
              status = cfnresponse.SUCCESS
              try:
                  source_bucket = event['ResourceProperties']['SourceBucket']
                  dest_bucket = event['ResourceProperties']['DestBucket']
                  prefix = event['ResourceProperties']['Prefix']
                  objects = event['ResourceProperties']['Objects']
                  if event['RequestType'] == 'Delete':
                      delete_objects(dest_bucket)
                  else:
                      copy_objects(source_bucket, dest_bucket, prefix, objects)
              except Exception as e:
                  logging.error('Exception: %s' % e, exc_info=True)
                  status = cfnresponse.FAILED
              finally:
                  timer.cancel()
                  cfnresponse.send(event, context, status, {}, None)

      Description: Copies objects from a source S3 bucket to a destination S3 bucket
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - CopyObjectsRole
          - Arn
      Runtime: python2.7
      Timeout: 240
    Type: AWS::Lambda::Function
  CopyObjectsRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:GetObject
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:aws:s3:::${QSS3BucketName}/${QSS3KeyPrefix}*
              - Action:
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - s3:DeleteObjectVersion
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource:
                  - Fn::Sub: arn:aws:s3:::${LambdaArtifactsBucket}/${QSS3KeyPrefix}*
                  - Fn::Sub: arn:aws:s3:::${LambdaArtifactsBucket}
            Version: '2012-10-17'
          PolicyName: object-copier
    Type: AWS::IAM::Role
  LambdaArtifactsBucket:
    Properties:
      Tags: []
      VersioningConfiguration:
        Status: Enabled
    Type: AWS::S3::Bucket
  CleanUpS3Bucket:
    Properties:
      DestBucket:
        Ref: LambdaArtifactsBucket
      ServiceToken:
        Fn::GetAtt:
          - CleanUpS3BucketFunction
          - Arn
    Type: AWS::CloudFormation::CustomResource
  CleanUpS3BucketFunction:
    Properties:
      Code:
        ZipFile: |
          import json
          import logging
          import threading
          import boto3
          import cfnresponse

          s3c = boto3.client('s3')


          def delete_non_versioned_objects(bucket):
              print("Collecting data from" + bucket)
              paginator = s3c.get_paginator('list_objects_v2')
              result = paginator.paginate(Bucket=bucket)
              objects = []
              for page in result:
                  try:
                      for k in page['Contents']:
                          objects.append({'Key': k['Key']})
                          print("deleting objects")
                          s3c.delete_objects(Bucket=bucket, Delete={'Objects': objects})
                          objects = []
                  except Exception as e:
                      print(e)


          def delete_versioned_objects(bucket):
              print("Collecting data from" + bucket)
              paginator = s3c.get_paginator('list_object_versions')
              result = paginator.paginate(Bucket=bucket)
              objects = []
              for page in result:
                  try:
                      for k in page['Versions']:
                          objects.append({'Key': k['Key'], 'VersionId': k['VersionId']})
                      try:
                          for k in page['DeleteMarkers']:
                              version = k['VersionId']
                              key = k['Key']
                              objects.append({'Key': key, 'VersionId': version})
                      except Exception as e:
                          print(e)
                      print("deleting objects")
                      s3c.delete_objects(Bucket=bucket, Delete={'Objects': objects})
                  except Exception as e:
                      print(e)


          def timeout(event, context):
              logging.error('Execution is about to time out, sending failure response to CloudFormation')
              cfnresponse.send(event, context, cfnresponse.FAILED, {}, None)


          def handler(event, context):
              # make sure we send a failure to CloudFormation if the function is going to timeout
              timer = threading.Timer((context.get_remaining_time_in_millis() / 1000.00) - 0.5, timeout, args=[event, context])
              timer.start()

              print('Received event: %s' % json.dumps(event))
              status = cfnresponse.SUCCESS
              try:
                  dest_bucket = event['ResourceProperties']['DestBucket']
                  if event['RequestType'] == 'Delete':
                      check_if_versioned = s3c.get_bucket_versioning(Bucket=dest_bucket)
                      print(check_if_versioned)
                      if 'Status' in check_if_versioned:
                          print(check_if_versioned['Status'])
                          print("This is a versioned Bucket")
                          delete_versioned_objects(dest_bucket)
                      else:
                          print("This is not a versioned bucket")
                          delete_non_versioned_objects(dest_bucket)
                  else:
                      print("Nothing to do")
              except Exception as e:
                  logging.error('Exception: %s' % e, exc_info=True)
                  status = cfnresponse.FAILED
              finally:
                  timer.cancel()
                  cfnresponse.send(event, context, status, {}, None)

      Description: Empty the S3 Bucket
      Handler: index.handler
      Role:
        Fn::GetAtt:
          - S3CleanUpRole
          - Arn
      Runtime: python2.7
      Timeout: 240
    Type: AWS::Lambda::Function
  S3CleanUpRole:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: "/"
      Policies:
        - PolicyDocument:
            Statement:
              - Action:
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketVersions
                  - s3:DeleteObjectVersion
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                Effect: Allow
                Resource:
                  - Fn::GetAtt:
                      - LambdaArtifactsBucket
                      - Arn
                  - Fn::Sub: arn:aws:s3:::*
            Version: '2012-10-17'
          PolicyName: Empty-bucket
    Type: AWS::IAM::Role
Outputs:
  LambdaArtifactsBucket:
    Description: S3 Bucket for the Lambda Function Code
    Value:
      Ref: LambdaArtifactsBucket
